# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yH-UfiSupCJuOxHtHYxd-F2aU8Hrwd5l
"""

# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2))/2
gray_img_01 [0, 0]

gray_img_02 = np.average(img, axis=2)
gray_img_02[0 , 0]

gray_img_03 = img[:, :, 0]*0.21 + img[:, :, 1]*0.72 + img[:, :, 2]*0.07
gray_img_03[0 , 0]

# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()

sales = data[:, 3]
max_value = np.max(sales)
print(max_value)
max_index = np.argmax(sales)
print(max_index)

tv = data[:, 0]
np.average(tv)

np.sum(sales >= 20)

radio = data[:, 1]
np.mean(radio[sales >= 15])

newspaper = data[:, 2]
avg_newspaper = np.mean(newspaper)
mask = newspaper > avg_newspaper
np.sum(newspaper[mask])

avg_sale = np.mean(sales)
scores = np.zeros(sales.shape, dtype=str)
scores[sales > avg_sale] = 'Good'
scores[sales < avg_sale] = 'Bad'
scores[sales == avg_sale] = 'Average'
print(scores[7:10])

A = sales[np.abs(sales - avg_sale).argmin()]

scores = np.zeros(sales.shape, dtype=str)
scores[sales > A] = 'Good'
scores[sales < A] = 'Bad'
scores[sales == A] = 'Average'
print(scores[7:10])

